#!/usr/bin/env php

<?php

require "vendor/autoload.php";

use GitlabChangelog\GitlabChangelog;

$changelog = new GitlabChangelog();
$changelog->url = "http://git.lelyonline.com/";
$changelog->repo = "mruitenb/portal-crm";
$changelog->token = "HJQTcJxKzuoFZEzxrfVW";

$changelog->getLabels = function ($issue) {
    $label = "Fixed";
    $map = array(
        "bug" => "Fixed",
        "enhancement" => "Improved",
        "feature" => "Added"
    );
    foreach ($map as $k => $v) {
        if (strripos(implode(',', $issue->labels), $k) !== false) {
            $label = $v;
            break;
        }
    }

    return array($label);
};

$markdown = $changelog->markdown();

file_put_contents("changelog.md", $markdown);